modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="microwave"
version="1.0.0"
displayName="Microwave Mod"
authors="Example"
description='''
Adds a functional microwave block to Minecraft.
'''

[[dependencies.microwave]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.microwave]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"